# src/main/resources/application.properties
# Active profile controlled by env var SPRING_PROFILES_ACTIVE
spring.application.name=clients-api
springdoc.swagger-ui.path=/docs

# JSON logging for Loki (always on)
logging.config=classpath:logback-spring.xml