apiVersion: v1
kind: Service
metadata:
  name: {{ include "clients-api.fullname" . }}
  labels:
    {{- include "clients-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "clients-api.selectorLabels" . | nindent 4 }}
